spring:
  mvc:
    pathmatch:
      matching-strategy: "ANT_PATH_MATCHER"
  datasource:
      url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/}
      username: ${POSTGRES_USER:user}
      password: ${POSTGRES_PASSWORD:password}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQL81Dialect

server:
  error:
    include-message: always