version: '3.7'

services:
#  app:
#    build: .
#    restart: on-failure
#    env_file:
#      - .env
#    ports:
#      - 3000:3000
#    volumes:
#      - ./:/usr/src/app
#    depends_on:
#      postgres:
#        condition: service_healthy

  postgres:
    image: postgres
    healthcheck:
      test: bash -c "pg_isready -U ${POSTGRES_USER}"
      interval: 1s
      timeout: 10s
      retries: 20
      start_period: 3s
    env_file:
      - .env
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres: